services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  broker:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  orderapi:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    working_dir: /app
    depends_on:
      - broker
      - rabbitmq
    ports:
      - "5001:8080"
    volumes:
      - .:/app
      - /app/OrderApi/bin
      - /app/OrderApi/obj
      - /app/Shared/bin
      - /app/Shared/obj
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      Kafka__BootstrapServers: broker:9092
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
    command: >
      sh -c "dotnet restore OrderApi/OrderApi.csproj &&
             dotnet watch --no-hot-reload run --project OrderApi/OrderApi.csproj --urls=http://0.0.0.0:8080"

  productapi:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    working_dir: /app
    depends_on:
      - broker
      - rabbitmq
    ports:
      - "5002:8080"
    volumes:
      - .:/app
      - /app/ProductApi/bin
      - /app/ProductApi/obj
      - /app/Shared/bin
      - /app/Shared/obj
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      Kafka__BootstrapServers: broker:9092
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
    command: >
      sh -c "dotnet restore ProductApi/ProductApi.csproj &&
             dotnet watch --no-hot-reload run --project ProductApi/ProductApi.csproj --urls=http://0.0.0.0:8080"